#! /bin/bash

############################################################
############################################################
# Functions                                                #
############################################################
############################################################

is_alive_ping()
{
  ping -c 3 $1 > /dev/null
  [ $? -eq 0 ] && echo Node with IP: $i is up.
}


Help()
{
   # Display Help
   echo "Written by Oliver Campbell [os.campbell@protonmail.com]"
   echo
   echo "This script will ping all hosts in your spcified netowrk (/24 only)"
   echo "and print out the public IP, ISP and a speed test."
   echo
   echo "Syntax:"
   echo "pingreport [IP address (network portion)] [Outlet or port]"
   echo
   echo "Example:"
   echo "pingreport 192.168.1 G/001"
   echo
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################

# Start the speedtest so we dont have to wait for it to run later
mkdir /tmp/pingreport
speedtest > /tmp/pingreport/speedtest &

############################################################
# Process the input options. Add options as needed.        #
############################################################

# Get the options
while getopts ":hn:" option; do
   case $option in
      h) # display Help
         Help
         exit;;
     \?) # Invalid option
         echo "Error: Invalid option, try with -h"
         exit;;
   esac
done



echo "Ping sweep from outlet $2" | boxes

for i in $1.{1..254}
do
is_alive_ping $i & disown
done

sleep 35

echo

# Speed test results

echo "Public IP:"
cat /tmp/pingreport/speedtest | grep Testing\ from | cut -c 14- | rev | cut -c 4- | rev
echo "
Speed test:"
cat /tmp/pingreport/speedtest | grep load:
rm /tmp/pingreport -r

echo "
Scan complete!"




## improvements: make options for the variables with -ip and -p
##               make the defaut IP to be taken from the ifconfig output
##               check for boxes dependency and run without it if missing
##               figure out a way to sort the ping responses numberically
##               check for speedtest dependency
